// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rfv.proto

package rfv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a93b2c1ab53e9c0f, []int{0}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Entries struct {
	Entries              []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entries) Reset()         { *m = Entries{} }
func (m *Entries) String() string { return proto.CompactTextString(m) }
func (*Entries) ProtoMessage()    {}
func (*Entries) Descriptor() ([]byte, []int) {
	return fileDescriptor_a93b2c1ab53e9c0f, []int{1}
}

func (m *Entries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entries.Unmarshal(m, b)
}
func (m *Entries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entries.Marshal(b, m, deterministic)
}
func (m *Entries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entries.Merge(m, src)
}
func (m *Entries) XXX_Size() int {
	return xxx_messageInfo_Entries.Size(m)
}
func (m *Entries) XXX_DiscardUnknown() {
	xxx_messageInfo_Entries.DiscardUnknown(m)
}

var xxx_messageInfo_Entries proto.InternalMessageInfo

func (m *Entries) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Entry struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a93b2c1ab53e9c0f, []int{2}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entry) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchRequest)(nil), "rfv.FetchRequest")
	proto.RegisterType((*Entries)(nil), "rfv.Entries")
	proto.RegisterType((*Entry)(nil), "rfv.Entry")
}

func init() { proto.RegisterFile("rfv.proto", fileDescriptor_a93b2c1ab53e9c0f) }

var fileDescriptor_a93b2c1ab53e9c0f = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xd1, 0x4a, 0x86, 0x40,
	0x10, 0x85, 0x7f, 0xfd, 0x31, 0x71, 0x92, 0xa0, 0x21, 0x42, 0x0c, 0x42, 0x96, 0x2e, 0xbc, 0x69,
	0x05, 0xeb, 0x15, 0x0c, 0xba, 0xf5, 0x11, 0xcc, 0xd1, 0x96, 0xcc, 0xb5, 0x75, 0x95, 0x7c, 0xfb,
	0xd8, 0x5d, 0x0c, 0xf9, 0xef, 0x76, 0xcf, 0x99, 0x39, 0xe7, 0x1b, 0x88, 0x54, 0xb7, 0xf2, 0x49,
	0x49, 0x2d, 0xf1, 0xac, 0xba, 0x35, 0x7d, 0xe8, 0xa5, 0xec, 0x07, 0x2a, 0xac, 0xd4, 0x2c, 0x5d,
	0x41, 0xdf, 0x93, 0xde, 0xdc, 0x04, 0x7b, 0x84, 0xf8, 0x8d, 0xf4, 0xc7, 0x67, 0x4d, 0x3f, 0x0b,
	0xcd, 0x1a, 0x6f, 0xc0, 0x17, 0x6d, 0xe2, 0x65, 0x5e, 0x1e, 0xd5, 0xbe, 0x68, 0x59, 0x01, 0x61,
	0x35, 0x6a, 0x25, 0x68, 0xc6, 0x27, 0x08, 0xc9, 0x3d, 0x13, 0x2f, 0x3b, 0xe7, 0xd7, 0x25, 0x70,
	0xd3, 0x64, 0xec, 0xad, 0xde, 0x2d, 0xf6, 0x0c, 0x81, 0x55, 0x2e, 0x93, 0xf0, 0x0e, 0x02, 0x2d,
	0xf4, 0x40, 0x89, 0x6f, 0x25, 0xf7, 0x29, 0xbf, 0x20, 0x72, 0x01, 0x34, 0x49, 0x7c, 0x05, 0xb0,
	0x30, 0xef, 0x63, 0x4b, 0xbf, 0x78, 0xcf, 0x1d, 0x38, 0xdf, 0xc1, 0x79, 0x65, 0xc0, 0xd3, 0xf8,
	0xbf, 0xd6, 0xf4, 0x9d, 0x30, 0x87, 0xc0, 0x6e, 0xe1, 0xad, 0x35, 0x8e, 0xe7, 0xa4, 0x07, 0x44,
	0x76, 0x6a, 0xae, 0x6c, 0xd2, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x2b, 0x38, 0x0c,
	0x22, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EntryRepoClient is the client API for EntryRepo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntryRepoClient interface {
	FetchIndex(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Entries, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Entry, error)
}

type entryRepoClient struct {
	cc *grpc.ClientConn
}

func NewEntryRepoClient(cc *grpc.ClientConn) EntryRepoClient {
	return &entryRepoClient{cc}
}

func (c *entryRepoClient) FetchIndex(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Entries, error) {
	out := new(Entries)
	err := c.cc.Invoke(ctx, "/rfv.EntryRepo/FetchIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryRepoClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Entry, error) {
	out := new(Entry)
	err := c.cc.Invoke(ctx, "/rfv.EntryRepo/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntryRepoServer is the server API for EntryRepo service.
type EntryRepoServer interface {
	FetchIndex(context.Context, *empty.Empty) (*Entries, error)
	Fetch(context.Context, *FetchRequest) (*Entry, error)
}

// UnimplementedEntryRepoServer can be embedded to have forward compatible implementations.
type UnimplementedEntryRepoServer struct {
}

func (*UnimplementedEntryRepoServer) FetchIndex(ctx context.Context, req *empty.Empty) (*Entries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchIndex not implemented")
}
func (*UnimplementedEntryRepoServer) Fetch(ctx context.Context, req *FetchRequest) (*Entry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}

func RegisterEntryRepoServer(s *grpc.Server, srv EntryRepoServer) {
	s.RegisterService(&_EntryRepo_serviceDesc, srv)
}

func _EntryRepo_FetchIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryRepoServer).FetchIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rfv.EntryRepo/FetchIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryRepoServer).FetchIndex(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryRepo_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryRepoServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rfv.EntryRepo/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryRepoServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntryRepo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rfv.EntryRepo",
	HandlerType: (*EntryRepoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchIndex",
			Handler:    _EntryRepo_FetchIndex_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _EntryRepo_Fetch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rfv.proto",
}
